test:
  facebook:
    app_id: "293705013980191"
    app_secret: "814c880e63f00f127f0287743dbecb04"
  twitter:
    api_id: "VeH9gXLE8Pqg7FXqf4QoA"
    api_secret: "zujxB5wOlRLjDVB8EKPZszD0X2UTGdul9gPk5FsXnkk"

development:
  facebook:
    app_id: "293705013980191"
    app_secret: "814c880e63f00f127f0287743dbecb04"
  twitter:
    api_id: "VeH9gXLE8Pqg7FXqf4QoA"
    api_secret: "zujxB5wOlRLjDVB8EKPZszD0X2UTGdul9gPk5FsXnkk"

staging:
  facebook:
    app_id: "293705013980191"
    app_secret: "814c880e63f00f127f0287743dbecb04"
  twitter:
    api_id: "VeH9gXLE8Pqg7FXqf4QoA"
    api_secret: "zujxB5wOlRLjDVB8EKPZszD0X2UTGdul9gPk5FsXnkk"

kratos:
  facebook:
    app_id: "293705013980191"
    app_secret: "814c880e63f00f127f0287743dbecb04"
  twitter:
    api_id: "VeH9gXLE8Pqg7FXqf4QoA"
    api_secret: "zujxB5wOlRLjDVB8EKPZszD0X2UTGdul9gPk5FsXnkk"

production:
  facebook:
    app_id: "293705013980191"
    app_secret: "814c880e63f00f127f0287743dbecb04"
  twitter:
    api_id: "VeH9gXLE8Pqg7FXqf4QoA"
    api_secret: "zujxB5wOlRLjDVB8EKPZszD0X2UTGdul9gPk5FsXnkk"